name: flutter_dollar
description: Keep state in your `build()` function.
version: 0.0.1
homepage: https://github.com/pinyin/flutter_dollar
author: Bo Bao <bob432091@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.11
  dollar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

